spring:
  cloud:
    config:
      uri: http://localhost:8761
  application:
    name: springler-core
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true